name: Lagrange Deployment

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/setup@v2
      - name: Build application
        run: pnpm run build
      - name: Create release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          path: dist
          filename: 'lagrange-${{ github.ref_name }}.zip'
      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'lagrange-${{ github.ref_name }}.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
