name: Release Testing

on:
  push:
    branches:
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build --if-present
      - name: Get current NPM package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: lagrange-${{ steps.package-version.outputs.current-version}}-SNAPSHOT-${{ github.sha }}
          path: dist
